=== WellBattle6/mm-data/data/forcegenerator/faction_rules/formationRulesetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:attributeGroup name="predicateAttributeGroup">
        <xs:attribute name="ifUnitType" type="xs:string" />
        <xs:attribute name="ifWeightClass" type="xs:string" />
        <xs:attribute name="ifRating" type="xs:string" />
        <xs:attribute name="ifFormation" type="xs:string" />
        <xs:attribute name="ifRole" type="xs:string" />
        <xs:attribute name="ifMotive" type="xs:string" />
        <xs:attribute name="ifAugmented" type="xs:boolean" />
        <xs:attribute name="ifDateBetween" type="xs:string" />
        <xs:attribute name="ifTopLevel" type="xs:boolean" />
        <xs:attribute name="ifName" type="xs:string" />
        <xs:attribute name="ifFaction" type="xs:string" />
        <xs:attribute name="ifFlags" type="xs:string" />
        <xs:attribute name="ifIndex" type="xs:string" />
    </xs:attributeGroup>

    <xs:attributeGroup name="assertionAttributeGroup">
        <xs:attribute name="unitType" type="xs:string" />
        <xs:attribute name="weightClass" type="xs:string" />
        <xs:attribute name="rating" type="xs:string" />
        <xs:attribute name="formation" type="xs:string" />
        <xs:attribute name="role" type="xs:string" />
        <xs:attribute name="motive" type="xs:string" />
        <xs:attribute name="augmented" type="xs:boolean" />
        <xs:attribute name="chassis" type="xs:string" />
        <xs:attribute name="model" type="xs:string" />
        <xs:attribute name="variant" type="xs:string" />
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="fluffName" type="xs:string" />
        <xs:attribute name="faction" type="xs:string" />
        <xs:attribute name="flags" type="xs:string" />
    </xs:attributeGroup>

    <xs:group name="ruleGroup">
        <xs:choice>
            <xs:element name="weightClass" type="optionGroupType" />
            <xs:element name="unitType" type="optionGroupType" />
            <xs:element name="chassis" type="optionGroupType" />
            <xs:element name="variant" type="optionGroupType" />
            <xs:element name="motive" type="optionGroupType" />
            <xs:element name="formation" type="optionGroupType" />
            <xs:element name="role" type="optionGroupType" />
            <xs:element name="flags" type="optionGroupType" />
            <xs:element name="changeEschelon" type="optionGroupType" />
        </xs:choice>
    </xs:group>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="defaults" />
                <xs:element minOccurs="0" maxOccurs="1" ref="customRanks" />
                <xs:element minOccurs="0" maxOccurs="1" ref="toc" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="force" />
            </xs:sequence>
            <xs:attribute name="faction" type="xs:string" />
            <xs:attribute name="parent" type="xs:string" />
            <xs:attribute name="ratingSystem">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="IS|SL|CLAN|ROS" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="defaults">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="unitType">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="echelon">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rankSystem">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rating">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="toc">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="unitType" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="echelon" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="rating" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="flags" type="tocType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="customRanks">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="base" type="xs:string" />
                <xs:element maxOccurs="unbounded" name="rank">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value=".+:.+" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="force">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="0"
                            maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="co" type="commanderType"
                            maxOccurs="unbounded" />
                <xs:element name="xo" type="commanderType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:group ref="ruleGroup"
                          minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="ruleGroup" type="ruleGroupType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="subforces" type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="attachedForces"
                            type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>

            <xs:attribute name="echelon" type="xs:string" use="required" />
            <xs:attribute name="eschName" type="xs:string" />
            <xs:attributeGroup ref="predicateAttributeGroup" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tocType">
        <xs:sequence>
            <xs:element name="option" type="tocOptionType"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocOptionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ifEschelon" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="commanderType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="position" type="xs:integer" />
                <xs:attribute name="title" type="xs:string" />
                <xs:attribute name="unitType" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ruleGroupType">
        <xs:sequence>
            <xs:group ref="ruleGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionGroupType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <!-- Deprecated alias for ifDateBetween (predicateAttributeGroup); kept for backwards compatibility. -->
                <xs:attribute name="ifYearBetween" type="xs:string" />
                <xs:attribute name="weight" type="xs:integer"
                              default="1" />
                <xs:attribute name="num" type="xs:integer" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="subforcesType">
        <xs:choice>
            <xs:element name="asFaction" type="xs:string" />
            <xs:element name="asParent" type="xs:string" />
            <xs:choice maxOccurs="unbounded">
                <xs:element name="subforce" type="subforceType" />
                <xs:element name="subforceOption"
                            type="subforceOptionType" />
            </xs:choice>
        </xs:choice>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

    <xs:complexType name="subforceType">
        <xs:simpleContent>
            <xs:extension base="eschelonDefinition">
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
                <xs:attribute name="num" type="xs:integer" default="1" />
                <xs:attribute name="generate" type="generateType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="generateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="model" />
            <xs:enumeration value="chassis" />
            <xs:enumeration value="group" />
            <xs:enumeration value="unit" />
            <xs:enumeration value="" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="eschelonDefinition">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+|%[A-Z_]+%)[+-^]?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="subforceOptionType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

</xs:schema>

=== WellBattle6/mm-data/data/forcegenerator/faction_rules/CFM.MiKrKl.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<ruleset faction="CFM.MiKrKl" ratingSystem="CLAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

    <defaults>
        <echelon>%CLUSTER%</echelon>
        <rankSystem>%RANK_CUSTOM%</rankSystem>
        <rating>FL</rating>
    </defaults>

    <toc>
        <unitType>
            <option ifDateBetween="3060,">null,Mek,ProtoMek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
            <option ifDateBetween="2870,3059">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
            <option ifDateBetween=",2869">null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
        </unitType>

        <echelon>
            <option ifUnitType="">%GALAXY%,%CLUSTER%</option>
            <option ifUnitType="BattleArmor">%CLUSTER%,%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
            <option ifUnitType="Mek|AeroSpaceFighter" ifDateBetween="2870,">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
            <option>%TRINARY%,%BINARY%,%STAR%</option>
        </echelon>

        <rating>
            <option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry" ifDateBetween="2900,">PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry">PG:Garrison,Sol:Solahma</option>
            <option ifEschelon="%GALAXY%"></option>
            <option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
        </rating>

        <flags>
            <option ifUnitType="null|Mek|BattleArmor" ifEschelon="%TRINARY%|%BINARY%">mixedMekBA:Combined Mek/BA unit</option>
            <option ifUnitType="null|Mek|AeroSpaceFighter" ifEschelon="%TRINARY%|%BINARY%">mixedMekAero:Combined Mek/Aero unit</option>
            <option ifUnitType="null|Mek|AeroSpaceFighter" ifEschelon="%STAR%|STAR^">mekAeroNova:Mek+Aero Nova</option>
        </flags>
    </toc>

    <force echelon="%GALAXY%" eschName="Kindraa">
        <co>%GALAXY_CMDR%</co>

        <subforces>
            <subforce role="command" rating="Keshik"
                      unitType="Mek" faction="CFM.Kl">%TRINARY%
            </subforce>
            <subforceOption>
                <option num="1" rating="FL"
                        faction="CFM.MiKr">%CLUSTER%
                </option>
                <option num="2" rating="FL"
                        faction="CFM.MiKr">%CLUSTER%
                </option>
            </subforceOption>
            <subforce num="1" rating="FL" faction="CFM.MiKr"
                      unitType="AeroSpaceFighter">%CLUSTER%
            </subforce>
            <subforce num="1" rating="FL" faction="CFM.MiKr"
                      unitType="BattleArmor">%CLUSTER%
            </subforce>
            <subforceOption>
                <option num="2" rating="SL"
                        faction="CFM.Kl">%CLUSTER%
                </option>
                <option num="3" rating="SL"
                        faction="CFM.Kl">%CLUSTER%
                </option>
            </subforceOption>
            <subforce rating="SL" faction="CFM.MiKr">%CLUSTER%</subforce>
        </subforces>

        <attachedForces>
            <!-- The Potemkin CFM Fire-Eater (Kindraa Kline) was renamed Jungle Heat after Kline
                 was absorbed into Kindraa Mick-Kreese-Kline (renamed by 3067). -->
            <subforce unitType="Warship" fluffName="CFM Jungle Heat"
                      chassis="Potemkin Troop Cruiser"
                      ifDateBetween=",3071">%ELEMENT%
            </subforce>
            <subforce unitType="Warship" fluffName="CFM Rancor"
                      chassis="Lola III Destroyer"
                      ifDateBetween=",3071">%ELEMENT%
            </subforce>
        </attachedForces>
    </force>
</ruleset>

=== WellBattle6/mm-data/data/forcegenerator/faction_rules/FID.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<ruleset faction="FID" ratingSystem="IS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

    <!--
    The Fidelis ("the faithful") are secret survivors of Clan Smoke Jaguar, reorganized on Wayside V
    by Star Colonel Paul Moon (the first Custos) after the 3060 annihilation. They equipped themselves
    from Goliath Scorpion isorla captured from the 35th Scorpion Cuirassiers (Rik Myers among the
    bondsmen). They field a single elite combined-arms Century - two Battle Groups of three Umbras
    each - with no Elementals and no aerospace (canon), plus one WarShip, the Flatus (a Dante-class
    frigate, ex-CSV Bordeaux).

    EQUIPMENT SOURCING BY ERA (faction= delegation; units come from the delegated faction's RAT):
      - Founding era (,3081): Goliath Scorpion isorla -> faction="CGS" (the "large majority" of their
        gear; CGS is available 2807-3080). CSJ is lore only - no RAT availability after its 3060
        annihilation, so it cannot be a generation source. Clan-isorla Umbras delegate a Clan %STAR%.
      - Republic-service era (3135+): re-equipped by the Republic of the Sphere -> faction="ROS" at
        rating "SB" (Stone's Brigade = A-rated, elite). ROS is IS-structured, so these Umbras delegate
        IS echelons (%LANCE%/%COMPANY%).

    The force is a %TOUMAN% (the whole single Century) so the WarShip attaches the proven way (cf. CB).
    -->

    <defaults>
        <unitType>Mek</unitType>
        <echelon>%TOUMAN%</echelon>
        <rankSystem>%RANK_CUSTOM%</rankSystem>
        <rating>A</rating>
    </defaults>

    <toc>
        <unitType>
            <option>null,Mek,Tank,VTOL,Infantry,BattleArmor,Warship,Dropship,Jumpship</option>
        </unitType>

        <echelon>
            <option ifUnitType="">%TOUMAN%,%TRINARY%</option>
            <option ifUnitType="Warship">%CLUSTER%,%STAR%</option>
            <option ifUnitType="Dropship|Jumpship">%STAR%</option>
            <option>%TRINARY%,%STAR%,%COMPANY%,%LANCE%</option>
        </echelon>

        <rating>
            <option>A</option>
        </rating>
    </toc>

    <!-- The Century: the Fidelis' whole force - two Battle Groups plus the Flatus. Modeled as a
         %TOUMAN% so the WarShip detachment attaches the same way it does for full Clan toumans. -->
    <force echelon="%TOUMAN%" eschName="Century">
        <co>%GALAXY_CMDR%</co>

        <subforces>
            <subforce num="2">%TRINARY%</subforce>
        </subforces>

        <attachedForces>
            <!-- The Flatus (Dante frigate, ex-CSV Bordeaux), lost 3149 at Dubhe to Clan Wolf. Only
                 present in the Republic-service era. -->
            <subforce unitType="Warship" ifDateBetween="3083,3149">%CLUSTER%</subforce>
        </attachedForces>
    </force>

    <!-- Battle Group: three combined-arms Umbras with armor and infantry support. Equipment is
         Goliath Scorpion isorla (,3081, as Clan stars) then Republic of the Sphere (3135+, as IS
         lances/companies at Stone's Brigade rating). -->
    <force echelon="%TRINARY%" eschName="Battle Group">
        <name>{ordinal} Battle Group</name>
        <co>%STAR_COL%</co>

        <weightClass>
            <option weight="2">H</option>
            <option weight="3">M</option>
            <option weight="1">L</option>
        </weightClass>

        <subforces>
            <!-- Founding era: Goliath Scorpion isorla (Clan front-line Mek stars). -->
            <subforce ifDateBetween=",3081" faction="CGS" rating="FL"
                      unitType="Mek" num="3" eschName="Umbra">%STAR%
            </subforce>
            <!-- Republic-service era: Republic of the Sphere, Stone's Brigade (A) rating. -->
            <subforce ifDateBetween="3135," faction="ROS" rating="SB"
                      unitType="Mek" num="3" eschName="Umbra">%LANCE%
            </subforce>
        </subforces>

        <attachedForces>
            <!-- Armor Umbra: era-sourced. -->
            <subforce ifDateBetween=",3081" faction="CGS" rating="SL"
                      unitType="Tank" name="Armor Umbra">%STAR%
            </subforce>
            <subforce ifDateBetween="3135," faction="ROS" rating="SB"
                      unitType="Tank" name="Armor Umbra">%LANCE%
            </subforce>
            <!-- Infantry Umbra: the Fidelis cross-train as infantry, which can be conventional or
                 Battle Armor. Founding era draws Scorpion conventional infantry; the Republic era
                 fields either Republic conventional infantry or Battle Armor. -->
            <subforce ifDateBetween=",3081" faction="CGS" rating="Sol"
                      unitType="Infantry" name="Infantry Umbra">%STAR%
            </subforce>
            <subforceOption ifDateBetween="3135,">
                <option faction="ROS" rating="SB" unitType="Infantry"
                        name="Infantry Umbra">%COMPANY%
                </option>
                <option faction="ROS" rating="SB" unitType="BattleArmor"
                        name="Battle Armor Umbra">%COMPANY%
                </option>
            </subforceOption>
        </attachedForces>
    </force>

    <!-- The Flatus: the Fidelis' sole WarShip, in Republic service. A Warship %CLUSTER% Fleet
         attached from the %TOUMAN% Century - the exact pattern CSA/CSJ use (verified to load). -->
    <force echelon="%CLUSTER%" eschName="Naval Detachment" ifUnitType="Warship">
        <name>Naval Detachment</name>
        <co>%GALAXY_CMDR%</co>

        <subforces>
            <subforce fluffName="Fidelis Flatus"
                      chassis="Dante Frigate">%ELEMENT%
            </subforce>
        </subforces>
    </force>

</ruleset>

=== WellBattle6/mm-data/data/forcegenerator/faction_rules/CFM.PBG.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<ruleset faction="CFM.PBG" ratingSystem="CLAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

    <defaults>
        <echelon>%CLUSTER%</echelon>
        <rankSystem>%RANK_CUSTOM%</rankSystem>
        <rating>FL</rating>
    </defaults>

    <toc>
        <unitType>
            <option ifDateBetween="3060,">null,Mek,ProtoMek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
            <option ifDateBetween="2870,3059">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
            <option ifDateBetween=",2869">null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
        </unitType>

        <echelon>
            <option ifUnitType="">%GALAXY%,%CLUSTER%</option>
            <option ifUnitType="Mek|AeroSpaceFighter" ifDateBetween="2870,">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
            <option>%TRINARY%,%BINARY%,%STAR%</option>
        </echelon>

        <rating>
            <option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry" ifDateBetween="2900,">PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry">PG:Garrison,Sol:Solahma</option>
            <option ifEschelon="%GALAXY%"></option>
            <option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
        </rating>

        <flags>
            <option ifUnitType="null|Mek|BattleArmor" ifEschelon="%TRINARY%|%BINARY%">mixedMekBA:Combined Mek/BA unit</option>
        </flags>
    </toc>

    <force echelon="%GALAXY%" eschName="Kindraa">
        <co>%GALAXY_CMDR%</co>

        <subforces>
            <subforce role="command" rating="Keshik"
                      unitType="Mek" faction="CFM.P">%TRINARY%
            </subforce>
            <subforceOption>
                <option num="1" rating="FL"
                        faction="CFM.P">%CLUSTER%
                </option>
                <option num="2" rating="FL"
                        faction="CFM.P">%CLUSTER%
                </option>
            </subforceOption>
            <subforce num="1" rating="FL" faction="CFM.BG"
                      unitType="AeroSpaceFighter">%CLUSTER%
            </subforce>
            <subforce num="1" rating="SL"
                      faction="CFM.BG">%CLUSTER%
            </subforce>
            <subforce num="1" rating="SL" flags="binary"
                      faction="CFM.BG">%CLUSTER%
            </subforce>
        </subforces>

        <attachedForces>
            <subforce unitType="Warship" fluffName="CFM Reaver"
                      chassis="Sovetskii Soyuz Heavy Cruiser">%ELEMENT%
            </subforce>
            <subforce unitType="Warship" fluffName="CFM Anathema"
                      chassis="Lola III Destroyer"
                      ifDateBetween=",3071">%ELEMENT%
            </subforce>
            <subforce unitType="Warship" fluffName="CFM Firehold"
                      chassis="Carrack Transport">%ELEMENT%
            </subforce>
        </attachedForces>
    </force>
</ruleset>
