=== WellBattle6/mm-data/data/forcegenerator/faction_rules/formationRulesetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
# MegaMek Data (C) 2025 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:attributeGroup name="predicateAttributeGroup">
        <xs:attribute name="ifUnitType" type="xs:string" />
        <xs:attribute name="ifWeightClass" type="xs:string" />
        <xs:attribute name="ifRating" type="xs:string" />
        <xs:attribute name="ifFormation" type="xs:string" />
        <xs:attribute name="ifRole" type="xs:string" />
        <xs:attribute name="ifMotive" type="xs:string" />
        <xs:attribute name="ifAugmented" type="xs:boolean" />
        <xs:attribute name="ifDateBetween" type="xs:string" />
        <xs:attribute name="ifTopLevel" type="xs:boolean" />
        <xs:attribute name="ifName" type="xs:string" />
        <xs:attribute name="ifFaction" type="xs:string" />
        <xs:attribute name="ifFlags" type="xs:string" />
        <xs:attribute name="ifIndex" type="xs:string" />
    </xs:attributeGroup>

    <xs:attributeGroup name="assertionAttributeGroup">
        <xs:attribute name="unitType" type="xs:string" />
        <xs:attribute name="weightClass" type="xs:string" />
        <xs:attribute name="rating" type="xs:string" />
        <xs:attribute name="formation" type="xs:string" />
        <xs:attribute name="role" type="xs:string" />
        <xs:attribute name="motive" type="xs:string" />
        <xs:attribute name="augmented" type="xs:boolean" />
        <xs:attribute name="chassis" type="xs:string" />
        <xs:attribute name="model" type="xs:string" />
        <xs:attribute name="variant" type="xs:string" />
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="fluffName" type="xs:string" />
        <xs:attribute name="faction" type="xs:string" />
        <xs:attribute name="flags" type="xs:string" />
    </xs:attributeGroup>

    <xs:group name="ruleGroup">
        <xs:choice>
            <xs:element name="weightClass" type="optionGroupType" />
            <xs:element name="unitType" type="optionGroupType" />
            <xs:element name="chassis" type="optionGroupType" />
            <xs:element name="variant" type="optionGroupType" />
            <xs:element name="motive" type="optionGroupType" />
            <xs:element name="formation" type="optionGroupType" />
            <xs:element name="role" type="optionGroupType" />
            <xs:element name="flags" type="optionGroupType" />
            <xs:element name="changeEschelon" type="optionGroupType" />
        </xs:choice>
    </xs:group>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="defaults" />
                <xs:element minOccurs="0" maxOccurs="1" ref="customRanks" />
                <xs:element minOccurs="0" maxOccurs="1" ref="toc" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="force" />
            </xs:sequence>
            <xs:attribute name="faction" type="xs:string" />
            <xs:attribute name="parent" type="xs:string" />
            <xs:attribute name="ratingSystem">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="IS|SL|CLAN|ROS" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="defaults">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="unitType">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="echelon">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rankSystem">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rating">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="toc">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="unitType" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="echelon" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="rating" type="tocType" />
                <xs:element minOccurs="0" maxOccurs="1" name="flags" type="tocType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="customRanks">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="base" type="xs:string" />
                <xs:element maxOccurs="unbounded" name="rank">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value=".+:.+" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="force">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="0"
                            maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup
                                        ref="predicateAttributeGroup" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="co" type="commanderType"
                            maxOccurs="unbounded" />
                <xs:element name="xo" type="commanderType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:group ref="ruleGroup"
                          minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="ruleGroup" type="ruleGroupType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="subforces" type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="attachedForces"
                            type="subforcesType"
                            minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>

            <xs:attribute name="echelon" type="xs:string" use="required" />
            <xs:attribute name="eschName" type="xs:string" />
            <xs:attributeGroup ref="predicateAttributeGroup" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tocType">
        <xs:sequence>
            <xs:element name="option" type="tocOptionType"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocOptionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ifEschelon" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="commanderType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="position" type="xs:integer" />
                <xs:attribute name="title" type="xs:string" />
                <xs:attribute name="unitType" type="xs:string" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ruleGroupType">
        <xs:sequence>
            <xs:group ref="ruleGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionGroupType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <!-- Deprecated alias for ifDateBetween (predicateAttributeGroup); kept for backwards compatibility. -->
                <xs:attribute name="ifYearBetween" type="xs:string" />
                <xs:attribute name="weight" type="xs:integer"
                              default="1" />
                <xs:attribute name="num" type="xs:integer" />
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="subforcesType">
        <xs:choice>
            <xs:element name="asFaction" type="xs:string" />
            <xs:element name="asParent" type="xs:string" />
            <xs:choice maxOccurs="unbounded">
                <xs:element name="subforce" type="subforceType" />
                <xs:element name="subforceOption"
                            type="subforceOptionType" />
            </xs:choice>
        </xs:choice>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

    <xs:complexType name="subforceType">
        <xs:simpleContent>
            <xs:extension base="eschelonDefinition">
                <xs:attributeGroup ref="predicateAttributeGroup" />
                <xs:attributeGroup ref="assertionAttributeGroup" />
                <xs:attribute name="num" type="xs:integer" default="1" />
                <xs:attribute name="generate" type="generateType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="generateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="model" />
            <xs:enumeration value="chassis" />
            <xs:enumeration value="group" />
            <xs:enumeration value="unit" />
            <xs:enumeration value="" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="eschelonDefinition">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+|%[A-Z_]+%)[+-^]?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="subforceOptionType">
        <xs:sequence>
            <xs:element name="option" type="optionType"
                        maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attributeGroup ref="predicateAttributeGroup" />
        <xs:attribute name="generate" type="generateType" />
    </xs:complexType>

</xs:schema>

=== WellBattle6/mm-data/data/forcegenerator/faction_rules/CWE.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
# MegaMek Data (C) 2026 by The MegaMek Team is licensed under CC BY-NC-SA 4.0.
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek Data was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
-->
<!--
    The Wolf Empire is Clan Wolf's Inner Sphere nation (declared 1 Jan 3142, faction
    active 3143+). Alaric Ward conquered 60+ worlds from the Free Worlds League and
    Lyran Commonwealth, capital Gienah, and by 3151 won the ilClan Trial and took Terra
    (115 systems), founding the Reborn Star League. This ruleset inherits the mature
    Clan Wolf (CW) file via parent="CW": clusters, trinaries, stars, weight composition,
    and the Naval Reserve all come from CW. CWE overrides only the touman, replacing CW's
    Invasion/Jihad galaxy roster with the Dark Age roster.

    Naval: inherited from CW. At 3143+ every Refusal-War/Jihad loss is already date-gated
    out, leaving the Dark Age survivors (Dire Wolf, Bloody Fang, Rogue, Jerome Winson,
    Victoria Ward) plus McKenna's Pride (gated 3077, in CW). No CWE naval block needed.

    Weight: inherited from CW (balanced-elite). Measure before adding any target; the
    Wolf Empire trends as a strong, well-rounded power, not a one-note assault Clan.

    Galaxy names (incl. nicknames and the non-greek Rufus/Lupus) are set literally in the
    touman; the inherited CW galaxy node's {greek} template only fills in when no name is
    set, so no override is needed. Remaining nicety (not done - high machinery, low value):
    per-galaxy Keshik command-unit names (Golden Keshik, Silver Keshik, etc.).
-->
<ruleset faction="CWE" parent="CW" ratingSystem="CLAN"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

    <defaults>
        <echelon>%CLUSTER%</echelon>
        <rankSystem>%RANK_CLAN%</rankSystem>
        <rating>FL</rating>
    </defaults>

    <toc>
        <unitType>
            <option>null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter,Warship,Dropship,Jumpship</option>
        </unitType>

        <echelon>
            <option ifUnitType="">%TOUMAN%,%GALAXY%,%CLUSTER%</option>
            <option ifUnitType="Warship">%CLUSTER%</option>
            <option ifUnitType="Jumpship|Dropship">%STAR%</option>
            <option ifUnitType="Mek">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
            <option>%TRINARY%,%BINARY%,%STAR%</option>
        </echelon>

        <rating>
            <option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
            <option ifUnitType="Infantry">PG:Garrison,Sol:Solahma</option>
            <option ifEschelon="%TOUMAN%"></option>
            <option ifEschelon="%GALAXY%">FL:Front Line,SL:Second Line,Sol:Solahma</option>
            <option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
        </rating>
    </toc>

    <!-- Dark Age touman roster (Clan Wolf Touman, 3145 table). Front-line: Alpha (Wolf
    Spirits, command), Beta (Shadow Wolves), Gamma (Wolf Hussars), Delta (Snarling Wolves).
    Second-line/garrison: Epsilon (Gray Wolves), Zeta, Kappa (Werewolves, formed 3063),
    Lambda, Mu, Sigma, Tau. Lupus (front-line) and Rufus (garrison) form 3151 on Gienah
    after the Terra conquest. Theta/Iota/Upsilon were destroyed in the ilClan Trial and are
    excluded. The galaxy name is set literally here (ForceNode applies the inherited node's
    {greek} template only when no name is set), so nicknames and non-greek names render. -->

    <force echelon="%TOUMAN%" eschName="Touman">
        <co>%KHAN%</co>
        <xo>%SAKHAN%</xo>

        <subforces>
            <subforce name="Alpha Galaxy (The Wolf Spirits)" rating="FL"
                      role="command">%GALAXY%
            </subforce>
            <subforce name="Beta Galaxy (The Shadow Wolves)" rating="FL">%GALAXY%</subforce>
            <subforce name="Gamma Galaxy (The Wolf Hussars)" rating="FL">%GALAXY%</subforce>
            <subforce name="Delta Galaxy (The Snarling Wolves)" rating="FL">%GALAXY%</subforce>
            <subforce name="Lupus Galaxy" rating="FL"
                      ifDateBetween="3151,">%GALAXY%
            </subforce>

            <subforce name="Epsilon Galaxy (The Gray Wolves)" rating="SL">%GALAXY%</subforce>
            <subforce name="Zeta Galaxy" rating="SL">%GALAXY%</subforce>
            <subforce name="Kappa Galaxy (The Werewolves)" rating="SL">%GALAXY%</subforce>
            <subforce name="Lambda Galaxy" rating="SL">%GALAXY%</subforce>
            <subforce name="Mu Galaxy" rating="SL">%GALAXY%</subforce>
            <subforce name="Sigma Galaxy" rating="SL">%GALAXY%</subforce>
            <subforce name="Tau Galaxy" rating="SL">%GALAXY%</subforce>
            <subforce name="Rufus Galaxy" rating="SL"
                      ifDateBetween="3151,">%GALAXY%
            </subforce>
        </subforces>

        <attachedForces>
            <subforce unitType="Warship">%CLUSTER%</subforce>
        </attachedForces>
    </force>
</ruleset>
